export enum GameActionTypes {
  ADD_CARD = 'ADD_CARD',
  ADD_TEAM = 'ADD_TEAM',
  ADD_PLAYER = 'ADD_PLAYER',
  ADD_ERROR = 'ADD-ERROR',
  REMOVE_CARD = 'REMOVE_CARD',
  REMOVE_TEAM = 'REMOVE_TEAM',
  REMOVE_PLAYER = 'REMOVE_PLAYER',
  REMOVE_ERROR = 'REMOVE_ERROR',
}
